# Generated by Django 6.0.6 on 2026-06-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vino',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=100)),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinoteca.vino')),
            ],
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
