# Generated by Django 6.0.6 on 2026-06-23 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0002_alter_bodega_descripcion_alter_vino_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='puntuacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vino',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
